#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: swagger #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:Mapper/**/*.xml
#  #3.JPA
#  jpa:
#    database: MySQL
#    show-sql: true
#    open-in-view: true
#  redis:
#    host: 127.0.0.1
#    port: 6379
#jwt:
#  config:
#    key: saas-ihrm
#    ttl: 3600000
